#!/usr/bin/env bash

# Run MetaPhlAn4 on shotgun metagenomics data to generate taxonomic and
# functional profiles.

set -euo pipefail

count_and_stream_reads() {
    # Assign arguments to descriptive local variables for clarity
    local input_fq_gz="$1"
    local count_output_file="$2"
    local length_threshold="$3"

    # Check if all arguments were provided
    if [ -z "$input_fq_gz" ] || [ -z "$count_output_file" ] || [ -z "$length_threshold" ]; then
        echo "Usage: count_and_stream_reads <input.fq.gz> <count_output_file> <length_threshold>" >&2
        return 1
    fi

    # Decompress the input file and pipe it to awk
    zcat "$input_fq_gz" | awk -v len_thresh="$length_threshold" '
        # Action 1: Print every line to stdout.
        # This ensures the data is passed through to the next command in the pipeline (e.g., bowtie2).
        {
            print
        }

        # Action 2: For sequence lines (every 4th line, starting at line 2),
        # check if the length meets the threshold.
        NR%4==2 && length($0) >= len_thresh {
            c++
        }

        # Action 3: After processing all lines, print the final count to stderr.
        END {
            print c+0 > "/dev/stderr"
        }
    ' 2> "$count_output_file" # Redirect stderr (the count) to the specified output file.
}

DATA_DIR="$HOME/dev/20250320_eb_summary/metagenomics_20260206"
METAPHLAN_BOWTIE2_DB=~/data/metaphlan/202403
METAPHLAN_BOWTIE2_INDEX=mpa_vJun23_CHOCOPhlAnSGB_202403
THREADS=16

mkdir -p "$DATA_DIR/metaphlan_with_host"
fqr1s=$(ls "$DATA_DIR/fastp/"*_1.fq.gz)
i=0
for READ1 in $fqr1s; do
    ((++i))
    READ2="${READ1%_1.fq.gz}_2.fq.gz"
    BASENAME=$(basename "$READ1")
    SAMPLE="${BASENAME%_1.fq.gz}"

    echo "Processing sample: $SAMPLE"

    TEMP_NUM1=$(mktemp)
    TEMP_NUM2=$(mktemp)

    # Suppress the SQ header lines of bowtie2 output.
    # -p<x> is using <x> cores for pbzip2. Let's default to 4 here.
    # ======== NOTE: I crafted the following command considering the following facts. ========
    # 1. The metaphlan database has millions of reference sequences. If SQ headers are 
    #   added to the output like we usually do, the output file will be very large and the 
    #   program will be unnecessarily slow.
    # 2. As per the specification of the SAM/BAM format, the SQ header lines are 
    #   required, and should immediately next to the HQ header line (@HD).
    # 3. Internally, MetaPhlAn's bowtie2 command does not write HD and SQ headers.
    # 4. Many programs will work without strictly following the specification, while 
    #   others don't. Specifically, samtools view will treat an entry as unmapped if its 
    #   RNAME does not match a SQ header (therefore the output will have to be SAM 
    #   instead of BAM. I don't want to reheader either); but samtools fastq still works 
    #   without any problems, though a ton of warnings will be printed.
    # 5. We should still comply with the SAM/BAM format specification as much as we can,
    #   so that the output is not too unintuitive to other people.
    # 6. Therefore, I compromise by just omitting the SQ headers from bowtie2 and manually 
    #   adding a dummy SQ header line after the HD header line. The output SAM will be 
    #   bzipped as seen commonly with MetaPhlAn.
    # 7. In this way, we violate the SAM/BAM format specification minimally while we 
    #   optimize the performance.
    # 8. Full SQ headers can still be generated from the fna file of the MetaPhlAn 
    #   database, so it's still possible to generate a complete SAM/BAM file.
    # ======== NOTE: Getting `--nreads` in the right way ========
    # By default, MetaPhlAn uses its util script read_fastx.py to concat all input fastq 
    # files by adding suffixes (file ordinal number and read ordinal number) to reads names, 
    # and at the end output to stderr some statistics, the first part of which will be the 
    # `nreads`. There is only one filtering done by this script: reads whose length is less 
    # than --read_min_len (default 70) are dropped.
    # So, I need to replicate this behavior. I do that by defining the above shell function 
    # `count_and_stream_reads`, which goes through the input and output all reads to stdout,
    # while recording the number of reads that are longer than `--read_min_len` and output 
    # to stderr at the end. I do this separately for read 1 and read 2, and add the stderr
    # to get `--nreads`. In this way, we only go through the input files once.
    # Alternatively, bowtie2 does support interleaved fastq input, so we could just run 
    # `count_and_stream_reads` once on the interleaved fastq file (e.g., generated by `seqtk mergepe`).
    # Alternatively, we should get the same number by running 
    # `samtools view -F 2304 | awk 'length($10) >= 70' | wc -l` on the above SAM file.
    bowtie2 \
        --very-sensitive \
        --seed 1992 \
        -x "$METAPHLAN_BOWTIE2_DB/$METAPHLAN_BOWTIE2_INDEX" \
        -1 <(count_and_stream_reads "$READ1" "$TEMP_NUM1" 70) \
        -2 <(count_and_stream_reads "$READ2" "$TEMP_NUM2" 70) \
        -p "$THREADS" \
        --sam-no-sq \
        2> /dev/null | \
        awk '
            /^@HD/ { print; print "@SQ\tSN:dummy\tLN:1"; next }
            { print }
        ' | pbzip2 -p4 > "$DATA_DIR/metaphlan_with_host/${SAMPLE}.dummy_sq.sam.bz2"

    NUM_GOOD_READ1=$(cat "$TEMP_NUM1")
    NUM_GOOD_READ2=$(cat "$TEMP_NUM2")
    rm -f "$TEMP_NUM1" "$TEMP_NUM2"
    NUM_GOOD_TOTAL=$((NUM_GOOD_READ1 + NUM_GOOD_READ2))

    # Dynamic bam to sam and read renaming
    # Cannot specify --force or --no_map here, since MetaPhlAn is taking input from stdin
    # Only mapped reads are needed for MetaPhlAn.
    pbzip2 -p4 -dc "$DATA_DIR/metaphlan_with_host/${SAMPLE}.dummy_sq.sam.bz2" | \
        awk 'BEGIN {OFS="\t"} {
            flag = $2;
            if (and(flag, 64)) { $1 = $1 "/1" }
            else if (and(flag, 128)) { $1 = $1 "/2" }
            print $0
        }' | \
        metaphlan \
            --input_type sam \
            -o "$DATA_DIR/metaphlan_with_host/${SAMPLE}.txt" \
            --nreads "$NUM_GOOD_TOTAL" \
            --db_dir "$METAPHLAN_BOWTIE2_DB" \
            --index "$METAPHLAN_BOWTIE2_INDEX" \
            2> /dev/null
    
    aws s3 cp \
        "$DATA_DIR/metaphlan_with_host/${SAMPLE}.dummy_sq.sam.bz2" \
        s3://yiming-qu/foli_ibs_metagenomics/metaphlan_with_host/ \
        > /dev/null
    rm -f "$DATA_DIR/metaphlan_with_host/${SAMPLE}.dummy_sq.sam.bz2"
done | tqdm --total "$(echo "$fqr1s" | wc -l)" > /dev/null

mkdir -p "$DATA_DIR/metaphlan"
fqr1s=$(ls "$DATA_DIR/fastp_no_host/"*_1.fq.gz)
i=0
for READ1 in $fqr1s; do
    ((++i))
    # Skip the first 1 sample
    # if [ $i -le 24 ]; then
    #     echo "Skipping sample $i: $READ1"
    #     continue
    # fi
    READ2="${READ1%_1.fq.gz}_2.fq.gz"
    BASENAME=$(basename "$READ1")
    SAMPLE="${BASENAME%_1.fq.gz}"

    echo "Processing sample: $SAMPLE"

    TEMP_NUM1=$(mktemp)
    TEMP_NUM2=$(mktemp)

    # Suppress the SQ header lines of bowtie2 output.
    # -p<x> is using <x> cores for pbzip2. Let's default to 4 here.
    # ======== NOTE: I crafted the following command considering the following facts. ========
    # 1. The metaphlan database has millions of reference sequences. If SQ headers are 
    #   added to the output like we usually do, the output file will be very large and the 
    #   program will be unnecessarily slow.
    # 2. As per the specification of the SAM/BAM format, the SQ header lines are 
    #   required, and should immediately next to the HQ header line (@HD).
    # 3. Internally, MetaPhlAn's bowtie2 command does not write HD and SQ headers.
    # 4. Many programs will work without strictly following the specification, while 
    #   others don't. Specifically, samtools view will treat an entry as unmapped if its 
    #   RNAME does not match a SQ header (therefore the output will have to be SAM 
    #   instead of BAM. I don't want to reheader either); but samtools fastq still works 
    #   without any problems, though a ton of warnings will be printed.
    # 5. We should still comply with the SAM/BAM format specification as much as we can,
    #   so that the output is not too unintuitive to other people.
    # 6. Therefore, I compromise by just omitting the SQ headers from bowtie2 and manually 
    #   adding a dummy SQ header line after the HD header line. The output SAM will be 
    #   bzipped as seen commonly with MetaPhlAn.
    # 7. In this way, we violate the SAM/BAM format specification minimally while we 
    #   optimize the performance.
    # 8. Full SQ headers can still be generated from the fna file of the MetaPhlAn 
    #   database, so it's still possible to generate a complete SAM/BAM file.
    # ======== NOTE: Getting `--nreads` in the right way ========
    # By default, MetaPhlAn uses its util script read_fastx.py to concat all input fastq 
    # files by adding suffixes (file ordinal number and read ordinal number) to reads names, 
    # and at the end output to stderr some statistics, the first part of which will be the 
    # `nreads`. There is only one filtering done by this script: reads whose length is less 
    # than --read_min_len (default 70) are dropped.
    # So, I need to replicate this behavior. I do that by defining the above shell function 
    # `count_and_stream_reads`, which goes through the input and output all reads to stdout,
    # while recording the number of reads that are longer than `--read_min_len` and output 
    # to stderr at the end. I do this separately for read 1 and read 2, and add the stderr
    # to get `--nreads`. In this way, we only go through the input files once.
    # Alternatively, bowtie2 does support interleaved fastq input, so we could just run 
    # `count_and_stream_reads` once on the interleaved fastq file (e.g., generated by `seqtk mergepe`).
    # Alternatively, we should get the same number by running 
    # `samtools view -F 2304 | awk 'length($10) >= 70' | wc -l` on the above SAM file.
    bowtie2 \
        --very-sensitive \
        --seed 1992 \
        -x "$METAPHLAN_BOWTIE2_DB/$METAPHLAN_BOWTIE2_INDEX" \
        -1 <(count_and_stream_reads "$READ1" "$TEMP_NUM1" 70) \
        -2 <(count_and_stream_reads "$READ2" "$TEMP_NUM2" 70) \
        -p "$THREADS" \
        --sam-no-sq \
        2> /dev/null | \
        awk '
            /^@HD/ { print; print "@SQ\tSN:dummy\tLN:1"; next }
            { print }
        ' | pbzip2 -p4 > "$DATA_DIR/metaphlan/${SAMPLE}.dummy_sq.sam.bz2"

    NUM_GOOD_READ1=$(cat "$TEMP_NUM1")
    NUM_GOOD_READ2=$(cat "$TEMP_NUM2")
    rm -f "$TEMP_NUM1" "$TEMP_NUM2"
    NUM_GOOD_TOTAL=$((NUM_GOOD_READ1 + NUM_GOOD_READ2))

    # Dynamic bam to sam and read renaming
    # Cannot specify --force or --no_map here, since MetaPhlAn is taking input from stdin
    # Only mapped reads are needed for MetaPhlAn.
    pbzip2 -p4 -dc "$DATA_DIR/metaphlan/${SAMPLE}.dummy_sq.sam.bz2" | \
        awk 'BEGIN {OFS="\t"} {
            flag = $2;
            if (and(flag, 64)) { $1 = $1 "/1" }
            else if (and(flag, 128)) { $1 = $1 "/2" }
            print $0
        }' | \
        metaphlan \
            --input_type sam \
            -o "$DATA_DIR/metaphlan/${SAMPLE}.txt" \
            --nreads "$NUM_GOOD_TOTAL" \
            --db_dir "$METAPHLAN_BOWTIE2_DB" \
            --index "$METAPHLAN_BOWTIE2_INDEX" \
            2> /dev/null
    
    aws s3 cp \
      "$DATA_DIR/metaphlan/${SAMPLE}.dummy_sq.sam.bz2" \
      s3://yiming-qu/foli_ibs_metagenomics/metaphlan/ \
      > /dev/null
    rm -f "$DATA_DIR/metaphlan/${SAMPLE}.dummy_sq.sam.bz2"
done | tqdm --total "$(echo "$fqr1s" | wc -l)" > /dev/null